import nodemailer from "nodemailer10";import {pool,query} from "../lib/db";import {queueMail} from "../lib/mail";import {syncJira} from "../lib/jira";import type {RequestRecord} from "../lib/types";
const smtp=process.env.SMTP_HOST?nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:process.env.SMTP_SECURE==="true",auth:process.env.SMTP_USER?{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS}:undefined,connectionTimeout:15000,socketTimeout:30000}):null;
let stopping=false,mailBusy=false,jiraBusy=false;
async function drain(){if(mailBusy||!smtp)return;mailBusy=true;try{await query(`UPDATE email_outbox SET state='pending' WHERE state='sending' AND next_attempt_at<now()-interval '15 minutes'`);const jobs=await query(`UPDATE email_outbox SET state='sending' WHERE id IN(SELECT id FROM email_outbox WHERE state IN('pending','failed') AND next_attempt_at<=now() AND attempts<10 ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT 25) RETURNING *`);for(const j of jobs.rows){try{await smtp.sendMail({from:process.env.SMTP_FROM,to:j.recipient,subject:j.subject,html:j.html,text:j.text_body,messageId:`<${j.id}@sankari-platform>`});await query(`UPDATE email_outbox SET state='sent',sent_at=now(),attempts=attempts+1,last_error=NULL WHERE id=$1`,[j.id]);}catch(e){const message=e instanceof Error?e.message:"SMTP error";await query(`UPDATE email_outbox SET state='failed',attempts=attempts+1,last_error=$2,next_attempt_at=now()+(least(attempts+1,8)||' minutes')::interval WHERE id=$1`,[j.id,message.slice(0,500)]);}}}finally{mailBusy=false;}}
async function sla(){const rows=await query<RequestRecord>(`SELECT * FROM requests WHERE resolved_at IS NULL AND closed_at IS NULL AND sla_due_at<now()+interval '2 hours'`);for(const r of rows.rows){const overdue=new Date(r.sla_due_at)<new Date(),admins=await query<{email:string}>(`SELECT email FROM users WHERE roles&&ARRAY['admin','agent']::text[] AND disabled_at IS NULL`);for(const a of admins.rows)await queueMail(`${overdue?'sla-overdue':'sla-warning'}:${r.sla_due_at}`,r,a.email,overdue?"SLA overdue":"SLA due soon",overdue?"This request is overdue.":"This request is due within two hours.");}}
async function jira(){if(jiraBusy)return;jiraBusy=true;try{const result=await syncJira();console.log("Jira sync",result);}catch(e){console.error("Jira sync failed",e instanceof Error?e.message:"Unknown error");}finally{jiraBusy=false;}}
async function canary(){if(!smtp||!process.env.ALERT_EMAIL)return;const key=new Date().toISOString().slice(0,10);const exists=await query(`SELECT 1 FROM system_state WHERE key=$1`,[`mail_canary:${key}`]);if(exists.rowCount)return;await smtp.sendMail({from:process.env.SMTP_FROM,to:process.env.ALERT_EMAIL,subject:"Sankari Platform daily mail check",text:`Notification delivery is working at ${new Date().toISOString()}.`});await query(`INSERT INTO system_state(key,value) VALUES($1,$2)`,[`mail_canary:${key}`,JSON.stringify({sentAt:new Date().toISOString()})]);}
async function tick(){if(stopping)return;await Promise.allSettled([drain(),sla(),canary()]);}
await tick();await jira();const mailTimer=setInterval(tick,30000),jiraTimer=setInterval(jira,Number(process.env.JIRA_POLL_MINUTES||10)*60000);for(const sig of ["SIGINT","SIGTERM"] as const)process.on(sig,async()=>{stopping=true;clearInterval(mailTimer);clearInterval(jiraTimer);await pool.end();process.exit(0)});
