const $=s=>document.querySelector(s),app=$('#app'),modal=$('#modal');
const storage={get(k){try{return localStorage.getItem(k);}catch{return null;}},set(k,v){try{localStorage.setItem(k,v);}catch{}}};
const state={me:null,config:null,rows:[],tab:'tracker',filter:'all',search:'',page:0,current:null,comments:[],lang:storage.get(`sankari_${KIND}_lang`)||'en',theme:storage.get(`sankari_${KIND}_theme`)||'system',dialog:null};
const LOGO_DARK_INK=BRAND['logo-dark'],LOGO_WHITE_INK=BRAND['logo-white'],CREST_WHITE=BRAND['crest-white'],CREST_DARK=BRAND['crest-dark'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const t=(key,vars={})=>Object.entries(vars).reduce((s,[k,v])=>s.replaceAll('{'+k+'}',v),STRINGS[state.lang]?.[key]||STRINGS.en[key]||key);
const uid=()=>crypto.randomUUID(),nowIso=()=>new Date().toISOString();
const fmtDate=iso=>iso?new Date(iso).toLocaleDateString(state.lang==='ar'?'ar-SY':'en-GB',{day:'2-digit',month:'short',year:'numeric'}):'—';
const fmtDateTime=iso=>iso?new Date(iso).toLocaleString(state.lang==='ar'?'ar-SY':'en-GB',{dateStyle:'medium',timeStyle:'short'}):'—';
const isDark=()=>state.theme==='dark'||(state.theme==='system'&&matchMedia('(prefers-color-scheme: dark)').matches);
function setBrandImages(){document.querySelectorAll('[data-logo]').forEach(el=>el.src=el.dataset.logo==='white'?LOGO_WHITE_INK:isDark()?LOGO_WHITE_INK:LOGO_DARK_INK);}
function applyLanguage(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==='ar'?'rtl':'ltr';storage.set(`sankari_${KIND}_lang`,state.lang);}
function applyTheme(){if(state.theme==='system')delete document.documentElement.dataset.theme;else document.documentElement.dataset.theme=state.theme;storage.set(`sankari_${KIND}_theme`,state.theme);setBrandImages();}
applyLanguage();applyTheme();matchMedia('(prefers-color-scheme: dark)').addEventListener('change',setBrandImages);
const active=r=>KIND==='email'?['new','assigned','inprogress','waiting','reopened'].includes(r.status):!['resolved','closed'].includes(r.status);
const late=r=>active(r)&&new Date(r.slaDueAt)<new Date();
const sla=r=>!active(r)?t('slaMet'):t(late(r)?'lateBy':'dueIn',{hours:Math.max(1,Math.ceil(Math.abs(Date.parse(r.slaDueAt)-Date.now())/3600000))});
const statuses=()=>Object.keys(state.config.flows);
const toast=(message)=>{const e=$('#toast');e.textContent=message;e.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>e.classList.remove('show'),5500);};
async function api(path,method='GET',body){const headers={'X-Sankari-Client':'1'};if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';const r=await fetch('/api'+path,{method,headers,body:body?(body instanceof FormData?body:JSON.stringify(body)):undefined,credentials:'same-origin'});const data=await r.json();if(!r.ok){if(r.status===401&&path!=='/login'){state.me=null;modal.close();render();}throw Object.assign(new Error(data.error||t('error')),{status:r.status});}return data;}
const requestApi=(path='',method='GET',body)=>api('/'+KIND+path,method,body);
const button=(action,label,cls='',extra='')=>`<button type="button" class="${cls}" data-action="${action}" ${extra}>${esc(t(label))}</button>`;
const options=(values,current,translate=true)=>values.map(v=>`<option value="${esc(v)}" ${v===current?'selected':''}>${esc(translate?t(v):v)}</option>`).join('');
function field(name,label,value='',opts={}){const {required=false,type='text',full=false,items,translate=true,placeholder='',readonly=false}=opts;const attr=`name="${name}" id="f-${name}" ${required?'required':''} ${readonly?'readonly':''}`;const control=items?`<select ${attr}>${required?`<option value="">${t('choose')}</option>`:''}${options(items,value,translate)}</select>`:type==='textarea'?`<textarea ${attr} maxlength="${name==='description'?12000:8000}" placeholder="${esc(placeholder)}">${esc(value)}</textarea>`:`<input ${attr} type="${type}" value="${esc(value)}" placeholder="${esc(placeholder)}" ${type==='password'?'minlength="12" maxlength="200" autocomplete="new-password"':type==='email'?'maxlength="254"':type==='text'?'maxlength="500"':''}>`;return `<div class="field ${full?'full':''}"><label for="f-${name}">${esc(t(label))} ${required?'<span class="required">*</span>':''}</label>${control}</div>`;}
const check=(name,label,value=false)=>`<label class="check"><input type="checkbox" name="${name}" ${value?'checked':''}>${esc(t(label))}</label>`;
const badge=s=>`<span class="badge ${esc(s)}">${esc(t(s))}</span>`;
function topActions(){return `<div class="top-actions">${button('language',state.lang==='en'?'العربية':'English','quiet')}${button('theme',isDark()?'☀':'☾','quiet','aria-label="'+esc(t('appearance'))+'"')}${state.me?button('account','account','quiet'):''}</div>`;}
function login(){return `<main class="login"><section class="login-story"><img class="brand-img" data-logo="white" alt="Sankari Holding"><div><div class="eyebrow">SANKARI HOLDING / ${KIND==='helpdesk'?'01':'02'}</div><h1 style="white-space:pre-line">${esc(t(KIND==='helpdesk'?'loginStory':'loginEmailStory'))}</h1><p>${esc(t('loginStorySub'))}</p></div><div class="eyebrow">${esc(t('internal'))}</div></section><section class="login-form"><div class="login-box">${topActions()}<div class="eyebrow">${esc(t(KIND))}</div><h2>${esc(t('welcome'))}</h2><p class="muted">${esc(t('loginSub'))}</p><form data-form="login">${field('email','emailAddress','',{required:true,type:'email'})}${field('password','password','',{required:true,type:'password'})}<div class="error" role="alert"></div><button class="primary" type="submit">${esc(t('signIn'))} →</button></form><p class="note">${esc(t('loginHelp'))}</p><p class="note"><a href="/${KIND==='helpdesk'?'email':'helpdesk'}">${esc(t(KIND==='helpdesk'?'email':'helpdesk'))} ↗</a></p></div></section></main>`;}
function render(){applyLanguage();if(!state.me){app.innerHTML=login();setBrandImages();return;}const other=KIND==='helpdesk'?'email':'helpdesk';app.innerHTML=`<div class="layout"><aside class="sidebar"><div class="brand"><img class="brand-img" data-logo alt="Sankari Holding"><span class="eyebrow">${esc(t('internal'))}</span></div><div class="workspace">${esc(t('workspace'))}</div><nav class="nav" aria-label="${esc(t('workspace'))}">${[['tracker','▦',t('tracker')],['new','＋',t(KIND==='helpdesk'?'newTicket':'newRequest')],...(state.me.isAdmin?[['settings','⚙',t('settings')]]:[])].map(([tab,icon,label])=>`<button data-action="tab" data-tab="${tab}" class="${state.tab===tab?'active':''}" ${state.tab===tab?'aria-current="page"':''}><span class="nav-icon">${icon}</span>${esc(label)}${tab==='tracker'?`<span class="nav-count">${state.rows.length}</span>`:''}</button>`).join('')}</nav><div class="sidebar-bottom"><a class="switch-app" href="/${other}"><span>${esc(t('switchApp'))}</span>${esc(t(other))} ↗</a><div class="user"><div class="avatar">${esc(state.me.name.split(' ').map(s=>s[0]).slice(0,2).join(''))}</div><div class="user-info"><strong>${esc(state.me.name)}</strong><span class="muted">${esc(t(state.me.isAdmin?'admin':'requesterRole'))}</span></div></div>${button('logout','logout','quiet small')}</div></aside><div><header class="topbar"><div class="breadcrumb">${esc(t('serviceDesk'))} <span aria-hidden="true"> / </span> <b>${esc(t(KIND))}</b></div>${topActions()}</header><main class="content">${!state.me.isAdmin?`<div class="role-banner">${esc(t('ownOnly'))}</div>`:''}<div id="view">${state.tab==='new'?newForm():state.tab==='settings'?settingsView():tracker()}</div><footer class="bottom-note"><span>${esc(t('footer'))}</span><span><span class="live-dot"></span>${esc(t('secureSession'))}</span></footer></main></div></div>`;setBrandImages();if(state.config?.branding?.accent)document.documentElement.style.setProperty('--accent',state.config.branding.accent);if(state.tab==='settings')loadSettingsExtra();}
function heading(title,sub,action=''){return `<div class="page-heading"><div><div class="eyebrow">${esc(t(KIND))} / ${esc(t(state.tab==='new'?'newRequest':state.tab))}</div><h1>${esc(t(title))}</h1><p class="muted">${esc(t(sub))}</p></div>${action||`<div class="date mono">${fmtDate(nowIso())}</div>`}</div>`;}
function filtered(){const q=state.search.toLowerCase();return state.rows.filter(r=>(state.filter==='all'||(state.filter==='overdue'?late(r):r.status===state.filter))&&(!q||[r.subject,r.requesterName,r.requesterEmail,r.company,r.department,r.employeeName,r.assigneeName].some(v=>v?.toLowerCase().includes(q))));}
function tracker(){const total=state.rows.length,counts=[total,state.rows.filter(r=>active(r)&&r.status!=='waiting').length,state.rows.filter(r=>r.status==='waiting').length,state.rows.filter(r=>!active(r)).length,state.rows.filter(late).length];return `${heading(KIND==='helpdesk'?'overview':'overviewEmail',KIND==='helpdesk'?'overviewSub':'overviewEmailSub',button('new',KIND==='helpdesk'?'newTicket':'newRequest','primary'))}<section class="stats" aria-label="${esc(t('tracker'))}">${['total','active','waiting','completed','overdue'].map((key,i)=>`<div class="stat ${i===0?'accent':''}"><div class="label">${esc(t(key))}<span>${['↗','◷','◌','✓','!'][i]}</span></div><div class="number">${counts[i].toLocaleString(state.lang)}</div><div class="hint">${esc(t(['allTime','beingHandled','awaitingReply','successfullyDone','needsAction'][i]))}</div></div>`).join('')}</section><section class="card"><div class="card-head"><div><h3>${esc(t('requests'))}</h3><p>${esc(t(state.me.isAdmin?'requestList':'myRequests'))}</p></div><div class="inline">${button('refresh','refresh','quiet small')}${button('export','export','small')}</div></div><div class="toolbar"><div class="chips">${['all',...statuses(),'overdue'].map(s=>`<button class="chip ${state.filter===s?'active':''}" data-action="filter" data-filter="${s}" aria-pressed="${state.filter===s}">${esc(t(s))}</button>`).join('')}</div><input class="search" type="search" id="search" aria-label="${esc(t('search'))}" placeholder="${esc(t('search'))}" value="${esc(state.search)}"></div><div id="table-area">${table()}</div></section>${counts[4]?`<section class="attention"><span class="symbol">◷</span><div><h3>${esc(t('attentionTitle'))}</h3><p>${esc(t('attentionText',{count:counts[4]}))}</p></div>${button('overdue','review','small')}</section>`:''}`;}
function table(){const rows=filtered(),start=state.page*15,visible=rows.slice(start,start+15);return rows.length?`<div class="table-wrap"><table><thead><tr>${['date','employee','subject','priority','status','assignee','sla','actions'].map(k=>`<th scope="col">${esc(t(k))}</th>`).join('')}</tr></thead><tbody>${visible.map(r=>`<tr><td class="mono" style="font-size:10px">${fmtDate(r.createdAt)}<small>#${esc(r.id.slice(0,8))}</small></td><td>${esc(r.employeeName||r.requesterName)}<small>${esc(r.department)} · ${esc(r.company)}</small></td><td class="subject"><button class="row-link" data-action="detail" data-id="${r.id}">${esc(r.subject)}</button><small>${esc(t(r.category||r.requestType))}</small></td><td><span class="priority ${r.priority}">${esc(t(r.priority))}</span></td><td>${badge(r.status)}</td><td>${esc(r.assigneeName||t('unassigned'))}</td><td class="mono ${late(r)?'overdue':''}" style="font-size:10px">${esc(sla(r))}</td><td>${button('detail','open','quiet small',`data-id="${r.id}"`)}</td></tr>`).join('')}</tbody></table></div><div class="footer-row"><span>${esc(t('showing',{count:visible.length,total:rows.length}))}</span><div class="inline">${button('previous','previous','quiet small',state.page===0?'disabled':'')}${button('next','next','quiet small',start+15>=rows.length?'disabled':'')}</div></div>`:`<div class="empty"><div class="empty-mark">${state.rows.length?'⌕':'✧'}</div><h2>${esc(t(state.rows.length?'noResults':'noRequests'))}</h2><p>${esc(t(state.rows.length?'noResultsText':'noRequestsText'))}</p>${!state.rows.length?button('new',KIND==='helpdesk'?'newTicket':'newRequest','primary'):''}</div>`;}
function requestFields(r={},edit=false){const dept=['it','hr','finance','operationsDept','sales','management','other'];return `<div class="fields">${field('requesterName','requesterName',r.requesterName||state.me.name,{required:true,readonly:!state.me.isAdmin})}${field('requesterEmail','requesterEmail',r.requesterEmail||state.me.email,{required:true,type:'email',readonly:!state.me.isAdmin})}${KIND==='email'?field('employeeName','employeeName',r.employeeName,{required:true})+field('employeePosition','employeePosition',r.employeePosition)+field('employeePhone','employeePhone',r.employeePhone,{type:'tel',placeholder:'+963…'}):''}${field('department','department',dept.includes(r.department)?r.department:r.department?'other':'',{required:true,items:dept})}<div id="other-department" class="field ${r.department&&!dept.includes(r.department)?'':'hidden'}">${field('departmentOther','otherDepartment',!dept.includes(r.department)?r.department:'')}</div>${field('company','company',r.company||'Sankari Holding',{required:true,items:state.config.companies,translate:false})}${field(KIND==='helpdesk'?'category':'requestType',KIND==='helpdesk'?'category':'requestType',r.category||r.requestType||'',{required:true,items:KIND==='helpdesk'?state.config.categories:state.config.types})}${field('priority','priority',r.priority||'medium',{required:true,items:['low','medium','high','urgent']})}${field('subject','subject',r.subject,{required:true,full:true,placeholder:t('subjectPlaceholder')})}${field('description','description',r.description,{required:true,full:true,type:'textarea',placeholder:t('descriptionPlaceholder')})}${!edit?`<div class="field full"><label for="attachment">${esc(t('attachment'))}</label><input id="attachment" name="file" type="file" accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.xlsx"><small class="muted">${esc(t('attachHint'))}</small></div>`:''}</div>`;}
function newForm(){return `${heading(KIND==='helpdesk'?'newTicket':'newRequest','requestSub')}<div class="form-layout"><form data-form="request" class="card"><div class="card-head"><div><h3>${esc(t('requestDetails'))}</h3><p>${esc(t('readOnlyEmail'))}</p></div><span class="eyebrow">01 / ${KIND==='helpdesk'?'IT':'EMAIL'}</span></div><div class="card-body">${requestFields()}<p class="note">${esc(t('privacyNote'))}</p><div class="error" role="alert"></div><div class="form-actions"><button class="primary" type="submit">${esc(t('submit'))} →</button></div></div></form><aside class="aside-card"><div class="eyebrow">${esc(t('targets'))}</div><h2>${esc(t('expectTitle'))}</h2><p>${esc(t('expectText'))}</p><div class="sla-list">${Object.entries(state.config.hours).map(([k,h])=>`<div><span class="priority ${k}">${esc(t(k))}</span><span class="mono">${esc(t('hours',{count:h}))}</span></div>`).join('')}</div><p class="note">${esc(t('slaNote'))}</p></aside></div>`;}
function settingsView(){return `${heading('settings','brandSub')}<div class="settings-grid"><section class="card"><div class="card-head"><h3>${esc(t('branding'))}</h3></div><div class="card-body"><img class="brand-img" data-logo alt="Sankari Holding"><div class="swatches"><div class="swatch" style="background:#b6602f"></div><div class="swatch" style="background:#a97c1f"></div><div class="swatch" style="background:#302b26"></div><div class="swatch" style="background:#ede8df"></div></div><form data-form="branding"><div class="fields" style="margin-top:20px">${field('organization','organization',state.config.branding.organization,{required:true})}${field('accent','accent',state.config.branding.accent,{type:'color'})}</div><div class="form-actions"><button class="primary">${esc(t('save'))}</button></div></form></div></section><section class="card"><div class="card-head"><h3>${esc(t('appearance'))} & ${esc(t('language'))}</h3></div><div class="card-body"><div class="field"><label for="theme-select">${esc(t('appearance'))}</label><select id="theme-select">${options(['system','light','dark'],state.theme)}</select></div><div class="field" style="margin-top:20px"><label for="lang-select">${esc(t('language'))}</label><select id="lang-select"><option value="en" ${state.lang==='en'?'selected':''}>English</option><option value="ar" ${state.lang==='ar'?'selected':''}>العربية</option></select></div><div id="operations" style="margin-top:25px"></div></div></section><section class="card wide"><div class="card-head"><div><h3>${esc(t('agents'))}</h3><p>${esc(t('agentsSub'))}</p></div><span class="mono">${state.config.agents.length}</span></div><div class="card-body"><div class="agents">${state.config.agents.map(a=>`<div class="agent"><div class="avatar">${esc(a.name.split(' ').map(s=>s[0]).slice(0,2).join(''))}</div><div><strong>${esc(a.name)}</strong><p>${esc(a.email)}</p></div>${a.isDefault?badge('defaultAgent'):''}</div>`).join('')}</div><form data-form="agent"><div class="fields">${field('name','name','',{required:true})}${field('email','emailAddress','',{required:true,type:'email'})}</div><div class="error" role="alert"></div><div class="form-actions"><button class="primary">${esc(t('addAgent'))}</button></div></form></div></section><section class="card wide"><div class="card-head"><div><h3>${esc(t('users'))}</h3><p>${esc(t('usersSub'))}</p></div></div><div class="card-body"><div id="users-list"></div><form data-form="user"><div class="fields">${field('name','name','',{required:true})}${field('email','emailAddress','',{required:true,type:'email'})}${field('password','temporaryPassword','',{required:true,type:'password'})}<div style="align-self:center">${check('isAdmin','adminAccess')}</div></div><div class="error" role="alert"></div><div class="form-actions"><button class="primary">${esc(t('addUser'))}</button></div></form></div></section></div>`;}
async function loadSettingsExtra(){try{const [users,ops]=await Promise.all([api('/users'),requestApi('/operations')]);if(!$('#users-list'))return;$('#users-list').innerHTML=users.map(u=>`<div class="agent"><div><strong>${esc(u.name)}</strong><p>${esc(u.email)} · ${esc(t(u.disabled?'disabled':u.isAdmin?'admin':'requesterRole'))}</p></div>${u.id!==state.me.id?`<div class="inline" style="margin-inline-start:auto">${button('toggle-user',u.disabled?'enable':'disable','small',`data-id="${u.id}" data-disabled="${!u.disabled}"`)}${button('reset-user','resetPassword','small',`data-id="${u.id}"`)}</div>`:''}</div>`).join('');$('#operations').innerHTML=`<h3>${esc(t('operations'))}</h3><p class="note">${esc(t(ops.smtpConfigured?'smtpReady':'smtpMissing'))}</p><p class="note">${esc(t('notificationSchedule'))}: <span class="mono">${esc(ops.schedule)}</span> UTC<br>${esc(t('jobId'))}: <span class="mono">${esc(ops.jobId)}</span><br>${esc(t('lastRun'))}: ${ops.scheduler?fmtDateTime(ops.scheduler.last_run_at):t('notRun')}</p><p class="note">${ops.mail.map(m=>`${esc(t(m.status))}: ${m.count}`).join(' · ')}</p>`;}catch(e){toast(e.message);}}
function showModal(title,body,mode='detail'){state.dialog=mode;modal.innerHTML=`<div class="modal-head"><div><div class="eyebrow">${esc(t(KIND))}</div><h2 id="modal-title">${esc(title)}</h2></div>${button('close-modal','×','quiet','aria-label="'+esc(t('closeDialog'))+'"')}</div><div class="modal-body">${body}</div>`;if(!modal.open)modal.showModal();}
function renderCommentsHtml(){return state.comments.length?state.comments.map(c=>`<article class="comment"><div class="comment-head"><strong>${esc(c.authorName)}</strong>${c.isAdmin?badge('it'):''}<time datetime="${esc(c.createdAt)}">${fmtDateTime(c.createdAt)}</time></div><div class="comment-body">${esc(c.body)}</div></article>`).join(''):`<p class="note">${esc(t('noComments'))}</p>`;}
let commentsTimer;function subscribeComments(id){clearInterval(commentsTimer);commentsTimer=setInterval(async()=>{if(!modal.open||state.dialog!=='detail')return;try{state.comments=await requestApi('/requests/'+id+'/comments');if($('#comments-list'))$('#comments-list').innerHTML=renderCommentsHtml();}catch{}},15000);}
async function detail(id){const [r,comments]=await Promise.all([requestApi('/requests/'+id),requestApi('/requests/'+id+'/comments')]);state.current=r;state.comments=comments;const url=new URL(location.href);url.searchParams.set(KIND==='helpdesk'?'ticket':'request',id);history.replaceState({},'',url);renderDetail();subscribeComments(id);}
const dl=(label,value)=>`<div><dt>${esc(t(label))}</dt><dd>${esc(value||'—')}</dd></div>`;
function renderDetail(){const r=state.current,pipeline=KIND==='helpdesk'?['new','assigned','inprogress','resolved','closed']:['new','assigned','inprogress','provisioned','whatsapp_sent','confirmed','closed'];let current=pipeline.indexOf(r.status);if(r.status==='waiting')current=2;if(r.status==='reopened')current=0;const actions=(state.config.flows[r.status]||[]).filter(a=>state.me.isAdmin||a==='reopen'||(KIND==='email'&&a==='confirm'));showModal(r.subject,`<div class="steps">${pipeline.map((s,i)=>`<div class="step ${i<=current?'done':''} ${i===current?'current':''}"><div class="step-dot"></div>${esc(t(s))}</div>`).join('')}</div><dl>${dl('requester',r.requesterName)}${dl('requesterEmail',r.requesterEmail)}${dl('company',r.company)}${dl('department',t(r.department))}${dl('priority',t(r.priority))}${dl('status',t(r.status))}${dl('assignee',r.assigneeName||t('unassigned'))}${dl('createdAt',fmtDateTime(r.createdAt))}${dl('slaDueAt',fmtDateTime(r.slaDueAt))}${dl(KIND==='helpdesk'?'category':'requestType',t(r.category||r.requestType))}${KIND==='email'?dl('employeeName',r.employeeName)+dl('employeePosition',r.employeePosition)+dl('employeePhone',r.employeePhone):''}${['assignedAt','resolvedAt','closedAt','reopenedAt','accountCreatedAt','whatsappSentAt','confirmedAt'].filter(k=>r[k]).map(k=>dl(k,fmtDateTime(r[k]))).join('')}</dl><div class="description">${esc(r.description)}</div>${r.attachment?`<p><a href="${esc(r.attachment.url)}">↓ ${esc(r.attachment.filename)}</a></p>`:''}${r.accountDetails?`<div class="account-card"><h3>${esc(t('accountDetails'))}</h3><dl>${Object.entries(r.accountDetails).filter(([k])=>k!=='createdBy').map(([k,v])=>dl(k==='email'?'accountEmail':k,typeof v==='boolean'?t(v?'yes':'no'):k==='mailboxType'?t(v):v)).join('')}</dl></div>`:''}${r.whatsapp?`<div class="description"><strong>${esc(t('whatsapp'))} · ${esc(r.whatsapp.phone)}</strong><br>${esc(r.whatsapp.message)}<br><small>${fmtDateTime(r.whatsapp.sentAt)}</small></div>`:''}<div class="action-row">${actions.map((a,i)=>button('workflow',a,i===0?'primary':'',`data-workflow="${a}"`)).join('')}${state.me.isAdmin?button('edit','edit','quiet'):''}${button('attachment','uploadReplace','quiet')}</div><section class="comments"><h3>${esc(t('comments'))}</h3><div id="comments-list">${renderCommentsHtml()}</div><form data-form="comment" class="comment-form"><label class="visually-hidden" for="comment-body">${esc(t('comments'))}</label><textarea id="comment-body" name="body" required maxlength="8000" placeholder="${esc(t('commentPlaceholder'))}"></textarea><div class="error" role="alert"></div><div class="form-actions"><button class="primary">${esc(t('sendComment'))}</button></div></form></section>`);}
function editModal(){showModal(t('edit'),`<p class="note">${esc(t('adminEditNote'))}</p><form data-form="edit">${requestFields(state.current,true)}<div class="error" role="alert"></div><div class="form-actions">${button('back','cancel') }<button class="primary">${esc(t('save'))}</button></div></form><p class="note">${esc(t('deleteWarning'))}</p>${button('delete','delete','danger small')}`,'edit');}
function workflowModal(action){const r=state.current;if(action==='assign'){showModal(t('assignTitle'),`<p class="muted">${esc(t('assignHelp'))}</p><form data-form="workflow" data-workflow="assign"><div class="field" style="margin-top:20px"><label for="agentId">${esc(t('selectAgent'))}</label><select id="agentId" name="agentId" required>${state.config.agents.map(a=>`<option value="${esc(a.id)}" ${a.id===r.assigneeId?'selected':''}>${esc(a.name)}</option>`).join('')}</select></div><div class="error" role="alert"></div><div class="form-actions">${button('back','cancel')}<button class="primary">${esc(t('assign'))}</button></div></form>`,'assign');return;}
 if(action==='provision'){const a=r.accountDetails||{};showModal(t('accountDetails'),`<p class="password-warning">${esc(t('accountNote'))}</p><form data-form="workflow" data-workflow="provision"><div class="fields">${field('email','accountEmail',a.email,{type:'email',required:true})}${field('domain','domain',a.domain,{required:true,placeholder:'sankari-holding.com'})}${field('mailboxType','mailboxType',a.mailboxType||'user',{items:['user','shared','resource'],required:true})}${field('workspaceLicense','workspaceLicense',a.workspaceLicense)}${field('aliases','aliases',a.aliases)}${field('groups','groups',a.groups)}${check('outlookConfigured','outlookConfigured',a.outlookConfigured)}${check('erpLinked','erpLinked',a.erpLinked)}${field('notes','notes',a.notes,{type:'textarea',full:true})}</div><div class="error" role="alert"></div><div class="form-actions">${button('back','cancel')}<button class="primary">${esc(t('markProvisioned'))}</button></div></form>`,'provision');return;}
 if(action==='whatsapp'){showModal(t('whatsappTitle'),`<p class="muted">${esc(t('whatsappHelp'))}</p><form data-form="workflow" data-workflow="whatsapp"><div class="fields">${field('phone','phone',r.whatsapp?.phone||r.employeePhone,{required:true,type:'tel',full:true,placeholder:'+963…'})}${field('message','message',t('whatsappDefault',{name:r.employeeName,email:r.accountDetails?.email}),{required:true,type:'textarea',full:true})}</div><a class="whatsapp-link" id="wa-link" href="https://wa.me/" target="_blank" rel="noopener noreferrer">${esc(t('openWhatsApp'))} ↗</a>${check('sentConfirmed','sentConfirmation')}<div class="error" role="alert"></div><div class="form-actions">${button('back','cancel')}<button class="primary">${esc(t('recordSent'))}</button></div></form>`,'whatsapp');updateWhatsApp();return;}
 return doWorkflow(action,{});
}
async function doWorkflow(action,body){await requestApi('/requests/'+state.current.id+'/actions','POST',{...body,action,if_version:state.current.version});await refresh();await detail(state.current.id);toast(t('saved'));}
function updateWhatsApp(){const form=modal.querySelector('form');if(state.dialog!=='whatsapp'||!form)return;const phone=form.elements.phone.value.replace(/\D/g,'');$('#wa-link').href='https://wa.me/'+phone+'?text='+encodeURIComponent(form.elements.message.value);}
async function refresh(){[state.rows,state.config]=await Promise.all([requestApi('/requests'),requestApi('/config')]);if(state.me)render();}
function closeModal(){modal.close();state.dialog=null;clearInterval(commentsTimer);const url=new URL(location.href);url.searchParams.delete(KIND==='helpdesk'?'ticket':'request');history.replaceState({},'',url);}
modal.addEventListener('cancel',()=>closeModal());
function accountModal(){showModal(t('account'),`<p>${esc(state.me.name)} · ${esc(state.me.email)}</p><form data-form="password"><div class="fields">${field('current','currentPassword','',{required:true,type:'password'})}${field('password','newPassword','',{required:true,type:'password'})}</div><div class="error" role="alert"></div><div class="form-actions"><button class="primary">${esc(t('changePassword'))}</button>${button('logout','logout')}</div></form>`,'account');}
async function handleError(e,form){if(e.status===409&&state.current){await detail(state.current.id);toast(t('conflict'));return;}const box=form?.querySelector('.error');if(box)box.textContent=e.message;else toast(e.message);}
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;const a=b.dataset.action;if(b.disabled)return;try{
 if(a==='language'){state.lang=state.lang==='en'?'ar':'en';render();if(modal.open&&state.dialog==='detail')renderDetail();return;}
 if(a==='theme'){state.theme=isDark()?'light':'dark';applyTheme();return;}
 if(a==='logout'){await api('/logout','POST',{});state.me=null;closeModal();render();return;}
 if(a==='account'){accountModal();return;}
 if(a==='tab'||a==='new'){state.tab=a==='new'?'new':b.dataset.tab;render();return;}
 if(a==='filter'||a==='overdue'){state.filter=a==='overdue'?'overdue':b.dataset.filter;state.page=0;render();return;}
 if(a==='next'||a==='previous'){state.page+=a==='next'?1:-1;$('#table-area').innerHTML=table();return;}
 if(a==='close-modal'){closeModal();return;}
 if(a==='back'){await detail(state.current.id);return;}
 if(a==='edit'){editModal();return;}
 if(a==='workflow'){await workflowModal(b.dataset.workflow);return;}
 if(a==='detail'){await detail(b.dataset.id);return;}
 if(a==='refresh'){await refresh();return;}
 if(a==='attachment'){showModal(t('uploadReplace'),`<form data-form="attachment"><input type="file" name="file" required accept=".pdf,.png,.jpg,.jpeg,.webp,.txt,.csv,.docx,.xlsx"><p class="note">${esc(t('attachHint'))}</p><div class="error" role="alert"></div><div class="form-actions">${button('back','cancel')}<button class="primary">${esc(t('upload'))}</button></div></form>`,'attachment');return;}
 if(a==='delete'){if(b.dataset.armed!=='true'){b.dataset.armed='true';b.textContent=t('deleteArmed');return;}await requestApi('/requests/'+state.current.id,'DELETE',{if_version:state.current.version});closeModal();await refresh();toast(t('saved'));return;}
 if(a==='toggle-user'){await api('/users/'+b.dataset.id,'PATCH',{disabled:b.dataset.disabled==='true'});await loadSettingsExtra();return;}
 if(a==='reset-user'){showModal(t('resetPassword'),`<form data-form="reset-user" data-id="${esc(b.dataset.id)}">${field('password','newPassword','',{required:true,type:'password'})}<div class="error" role="alert"></div><div class="form-actions"><button class="primary">${esc(t('save'))}</button></div></form>`,'reset-user');return;}
 if(a==='export'){const cols=['id','createdAt','requesterName','requesterEmail','employeeName','department','company','subject','priority','status','assigneeName','slaDueAt'];const safe=v=>'"'+String(v??'').replace(/^[=+@\-\t\r]/,"'$&").replaceAll('"','""')+'"';const csv='\uFEFF'+[cols,...filtered().map(r=>cols.map(c=>r[c]??''))].map(row=>row.map(safe).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download=`sankari-${KIND}-${nowIso().slice(0,10)}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 }catch(err){await handleError(err);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){state.search=e.target.value;state.page=0;$('#table-area').innerHTML=table();}if(state.dialog==='whatsapp')updateWhatsApp();});
document.addEventListener('change',e=>{if(e.target.name==='department'){const box=$('#other-department');box?.classList.toggle('hidden',e.target.value!=='other');if(box)box.querySelector('input').required=e.target.value==='other';}if(e.target.id==='theme-select'){state.theme=e.target.value;applyTheme();}if(e.target.id==='lang-select'){state.lang=e.target.value;render();}});
async function uploadFile(id,file,version){if(file.size>10*1024*1024)throw new Error(t('attachHint'));const body=new FormData();body.set('file',file);body.set('if_version',version);return requestApi('/requests/'+id+'/attachment','POST',body);}
async function addComment(body){await requestApi('/requests/'+state.current.id+'/comments','POST',{body,if_version:state.current.version});await detail(state.current.id);await refresh();toast(t('commentAdded'));}
document.addEventListener('submit',async e=>{const form=e.target.closest('[data-form]');if(!form)return;e.preventDefault();const submit=form.querySelector('button[type=submit],button:not([type])'),kind=form.dataset.form,fd=new FormData(form),data=Object.fromEntries(fd);if(submit)submit.disabled=true;const error=form.querySelector('.error');if(error)error.textContent='';try{
 if(kind==='login'){state.me=await api('/login','POST',data);await refresh();const id=new URL(location.href).searchParams.get(KIND==='helpdesk'?'ticket':'request');if(id)await detail(id);}
 if(kind==='request'||kind==='edit'){if(data.department==='other')data.department=data.departmentOther;delete data.departmentOther;const file=fd.get('file');delete data.file;if(kind==='request'){if(file?.size>10*1024*1024)throw new Error(t('attachHint'));let r=await requestApi('/requests','POST',data),failed=false;if(file?.size){try{r=await uploadFile(r.id,file,r.version);}catch{failed=true;}}state.tab='tracker';await refresh();await detail(r.id);toast(t(failed?'uploadFailed':'created'));}else{await requestApi('/requests/'+state.current.id,'PATCH',{...data,if_version:state.current.version});await refresh();await detail(state.current.id);toast(t('saved'));}}
 if(kind==='comment')await addComment(data.body);
 if(kind==='workflow'){const action=form.dataset.workflow;if(action==='provision'){data.outlookConfigured=fd.has('outlookConfigured');data.erpLinked=fd.has('erpLinked');await doWorkflow(action,{accountDetails:data});}else{data.sentConfirmed=fd.has('sentConfirmed');await doWorkflow(action,data);}}
 if(kind==='attachment'){await uploadFile(state.current.id,fd.get('file'),state.current.version);await detail(state.current.id);toast(t('saved'));}
 if(kind==='agent'){await requestApi('/agents','POST',data);await refresh();toast(t('saved'));}
 if(kind==='branding'){await requestApi('/branding','PATCH',data);await refresh();toast(t('saved'));}
 if(kind==='user'){data.isAdmin=fd.has('isAdmin');await api('/users','POST',data);form.reset();await loadSettingsExtra();toast(t('saved'));}
 if(kind==='password'){await api('/password','POST',data);state.me=null;closeModal();render();toast(t('passwordChanged'));}
 if(kind==='reset-user'){await api('/users/'+form.dataset.id,'PATCH',data);closeModal();toast(t('resetDone'));}
 }catch(err){await handleError(err,form);}finally{if(submit)submit.disabled=false;}});
async function boot(){try{state.me=await api('/me');await refresh();const id=new URL(location.href).searchParams.get(KIND==='helpdesk'?'ticket':'request');if(id)await detail(id);}catch(e){if(e.status!==401)toast(e.message);render();}}
setInterval(async()=>{if(!state.me||state.tab!=='tracker'||modal.open||document.hidden)return;try{state.rows=await requestApi('/requests');if($('#table-area')){const focus=document.activeElement; if(focus?.id==='search')$('#table-area').innerHTML=table();else $('#view').innerHTML=tracker();}}catch{}},20000);
boot();
